-- ============================================================
-- NEXUS Cloud-Native Microservices Platform
-- PostgreSQL Schema Initialization
-- ============================================================
--
-- This script runs automatically when the PostgreSQL container
-- initializes for the first time.
--
-- It creates the logical schemas used by the NEXUS services.
-- ============================================================


CREATE SCHEMA IF NOT EXISTS identity;

CREATE SCHEMA IF NOT EXISTS registry;

CREATE SCHEMA IF NOT EXISTS incidents;

CREATE SCHEMA IF NOT EXISTS notifications;

CREATE SCHEMA IF NOT EXISTS audit;


COMMENT ON SCHEMA identity IS
'Stores NEXUS users, roles, authentication events, and identity-related records.';

COMMENT ON SCHEMA registry IS
'Stores registered services, support teams, environments, and service-health records.';

COMMENT ON SCHEMA incidents IS
'Stores operational incidents, assignments, status history, and resolution records.';

COMMENT ON SCHEMA notifications IS
'Stores notifications, processing status, retry attempts, and delivery history.';

COMMENT ON SCHEMA audit IS
'Stores append-oriented audit events generated by NEXUS services.';