"""Add API health composite indexes

Revision ID: 15c05d7c9167
Revises: f2be6dd724e8
Create Date: 2026-07-17 15:26:39.216182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c05d7c9167'
down_revision: Union[str, Sequence[str], None] = 'f2be6dd724e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_health_service_checked_at', 'api_health', ['service_id', 'checked_at'], unique=False, schema='registry')
    op.create_index('ix_api_health_status_checked_at', 'api_health', ['status', 'checked_at'], unique=False, schema='registry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_health_status_checked_at', table_name='api_health', schema='registry')
    op.drop_index('ix_api_health_service_checked_at', table_name='api_health', schema='registry')
    # ### end Alembic commands ###
