"""create remaining governance tables

Revision ID: 35e9d09a065b
Revises: bdb2ceae942f
Create Date: 2026-07-17 16:58:15.145677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e9d09a065b'
down_revision: Union[str, Sequence[str], None] = 'bdb2ceae942f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_number", sa.String(length=20), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("issue_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=25), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("assigned_team", sa.String(length=150), nullable=True),
        sa.Column("owner", sa.String(length=150), nullable=True),
        sa.Column("remediation_plan", sa.Text(), nullable=True),
        sa.Column("estimated_effort_hours", sa.Float(), nullable=True),
        sa.Column("actual_effort_hours", sa.Float(), nullable=True),
        sa.Column("target_resolution_date", sa.DateTime(), nullable=True),
        sa.Column("actual_resolution_date", sa.DateTime(), nullable=True),
        sa.Column("overdue", sa.Boolean(), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.incidents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["registry.services.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="incidents",
    )
    op.create_index(op.f('ix_incidents_issues_assigned_team'), 'issues', ['assigned_team'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_correlation_id'), 'issues', ['correlation_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_issue_number'), 'issues', ['issue_number'], unique=True, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_issue_type'), 'issues', ['issue_type'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_overdue'), 'issues', ['overdue'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_owner'), 'issues', ['owner'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_priority'), 'issues', ['priority'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_service_id'), 'issues', ['service_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_severity'), 'issues', ['severity'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_issues_status'), 'issues', ['status'], unique=False, schema='incidents')
    op.create_index('ix_issues_incident_id', 'issues', ['incident_id'], unique=False, schema='incidents')
    op.create_index('ix_issues_service_created', 'issues', ['service_id', 'created_at'], unique=False, schema='incidents')
    op.create_index('ix_issues_status_priority', 'issues', ['status', 'priority'], unique=False, schema='incidents')
    op.create_index('ix_issues_status_severity', 'issues', ['status', 'severity'], unique=False, schema='incidents')
    op.create_table('changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_number', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('change_category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=25), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('validation_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('implementation_team', sa.String(length=150), nullable=True),
    sa.Column('requested_by', sa.String(length=150), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(), nullable=True),
    sa.Column('outage_required', sa.Boolean(), nullable=False),
    sa.Column('outage_duration_minutes', sa.String(length=10), nullable=True),
    sa.Column('implementation_successful', sa.Boolean(), nullable=False),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_completed', sa.Boolean(), nullable=False),
    sa.Column('post_implementation_review', sa.Text(), nullable=True),
    sa.Column('customer_notification_sent', sa.Boolean(), nullable=False),
    sa.Column('emergency_change', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['incidents.issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='incidents'
    )
    op.create_index('ix_changes_approval_status', 'changes', ['approval_status', 'status'], unique=False, schema='incidents')
    op.create_index('ix_changes_issue_id', 'changes', ['issue_id'], unique=False, schema='incidents')
    op.create_index('ix_changes_service_planned_start', 'changes', ['service_id', 'planned_start_at'], unique=False, schema='incidents')
    op.create_index('ix_changes_status_risk_level', 'changes', ['status', 'risk_level'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_approval_status'), 'changes', ['approval_status'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_approved_by'), 'changes', ['approved_by'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_change_category'), 'changes', ['change_category'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_change_number'), 'changes', ['change_number'], unique=True, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_change_type'), 'changes', ['change_type'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_correlation_id'), 'changes', ['correlation_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_implementation_team'), 'changes', ['implementation_team'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_planned_start_at'), 'changes', ['planned_start_at'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_requested_by'), 'changes', ['requested_by'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_risk_level'), 'changes', ['risk_level'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_service_id'), 'changes', ['service_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_changes_status'), 'changes', ['status'], unique=False, schema='incidents')
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_number', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('methodology', sa.String(length=100), nullable=True),
    sa.Column('risk_owner', sa.String(length=150), nullable=False),
    sa.Column('business_owner', sa.String(length=150), nullable=True),
    sa.Column('assessed_by', sa.String(length=150), nullable=False),
    sa.Column('likelihood_score', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('inherent_risk_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('control_effectiveness', sa.Integer(), nullable=False),
    sa.Column('residual_risk_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overall_risk_rating', sa.String(length=25), nullable=False),
    sa.Column('risk_statement', sa.Text(), nullable=True),
    sa.Column('key_controls', sa.Text(), nullable=True),
    sa.Column('identified_gaps', sa.Text(), nullable=True),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_review_date', sa.DateTime(), nullable=True),
    sa.Column('risk_accepted', sa.Boolean(), nullable=False),
    sa.Column('executive_approval', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['incidents.issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='incidents'
    )
    op.create_index(op.f('ix_incidents_risk_assessments_assessment_number'), 'risk_assessments', ['assessment_number'], unique=True, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_assessment_type'), 'risk_assessments', ['assessment_type'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_correlation_id'), 'risk_assessments', ['correlation_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_next_review_date'), 'risk_assessments', ['next_review_date'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_overall_risk_rating'), 'risk_assessments', ['overall_risk_rating'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_risk_owner'), 'risk_assessments', ['risk_owner'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_service_id'), 'risk_assessments', ['service_id'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_risk_assessments_status'), 'risk_assessments', ['status'], unique=False, schema='incidents')
    op.create_index('ix_risk_assessments_issue', 'risk_assessments', ['issue_id'], unique=False, schema='incidents')
    op.create_index('ix_risk_assessments_owner', 'risk_assessments', ['risk_owner'], unique=False, schema='incidents')
    op.create_index('ix_risk_assessments_rating', 'risk_assessments', ['overall_risk_rating'], unique=False, schema='incidents')
    op.create_index('ix_risk_assessments_review', 'risk_assessments', ['next_review_date'], unique=False, schema='incidents')
    op.create_index('ix_risk_assessments_service_status', 'risk_assessments', ['service_id', 'status'], unique=False, schema='incidents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_assessments_service_status', table_name='risk_assessments', schema='incidents')
    op.drop_index('ix_risk_assessments_review', table_name='risk_assessments', schema='incidents')
    op.drop_index('ix_risk_assessments_rating', table_name='risk_assessments', schema='incidents')
    op.drop_index('ix_risk_assessments_owner', table_name='risk_assessments', schema='incidents')
    op.drop_index('ix_risk_assessments_issue', table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_status'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_service_id'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_risk_owner'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_overall_risk_rating'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_next_review_date'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_correlation_id'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_assessment_type'), table_name='risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_risk_assessments_assessment_number'), table_name='risk_assessments', schema='incidents')
    op.drop_table('risk_assessments', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_status'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_service_id'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_risk_level'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_requested_by'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_planned_start_at'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_implementation_team'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_correlation_id'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_change_type'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_change_number'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_change_category'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_approved_by'), table_name='changes', schema='incidents')
    op.drop_index(op.f('ix_incidents_changes_approval_status'), table_name='changes', schema='incidents')
    op.drop_index('ix_changes_status_risk_level', table_name='changes', schema='incidents')
    op.drop_index('ix_changes_service_planned_start', table_name='changes', schema='incidents')
    op.drop_index('ix_changes_issue_id', table_name='changes', schema='incidents')
    op.drop_index('ix_changes_approval_status', table_name='changes', schema='incidents')
    op.drop_table('changes', schema='incidents')
    op.drop_index('ix_issues_status_severity', table_name='issues', schema='incidents')
    op.drop_index('ix_issues_status_priority', table_name='issues', schema='incidents')
    op.drop_index('ix_issues_service_created', table_name='issues', schema='incidents')
    op.drop_index('ix_issues_incident_id', table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_status'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_severity'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_service_id'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_priority'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_owner'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_overdue'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_issue_type'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_issue_number'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_correlation_id'), table_name='issues', schema='incidents')
    op.drop_index(op.f('ix_incidents_issues_assigned_team'), table_name='issues', schema='incidents')
    op.drop_table('issues', schema='incidents')
    # ### end Alembic commands ###
