"""add operational governance tables

Revision ID: 7ee319994fcd
Revises: 15c05d7c9167
Create Date: 2026-07-17 16:41:20.993294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ee319994fcd'
down_revision: Union[str, Sequence[str], None] = '15c05d7c9167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('incident_number', sa.String(length=20), nullable=False), schema='incidents')
    op.add_column('incidents', sa.Column('incident_type', sa.String(length=100), nullable=False), schema='incidents')
    op.add_column('incidents', sa.Column('priority', sa.String(length=10), nullable=False), schema='incidents')
    op.add_column('incidents', sa.Column('detected_by', sa.String(length=150), nullable=True), schema='incidents')
    op.add_column('incidents', sa.Column('root_cause', sa.Text(), nullable=True), schema='incidents')
    op.add_column('incidents', sa.Column('customer_impact', sa.Text(), nullable=True), schema='incidents')
    op.add_column('incidents', sa.Column('resolution_summary', sa.Text(), nullable=True), schema='incidents')
    op.add_column('incidents', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False), schema='incidents')
    op.add_column('incidents', sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False), schema='incidents')
    op.add_column('incidents', sa.Column('duration_minutes', sa.Integer(), nullable=True), schema='incidents')
    op.add_column('incidents', sa.Column('sla_breached', sa.Boolean(), nullable=False), schema='incidents')
    op.create_index(op.f('ix_incidents_incidents_incident_number'), 'incidents', ['incident_number'], unique=True, schema='incidents')
    op.create_index(op.f('ix_incidents_incidents_incident_type'), 'incidents', ['incident_type'], unique=False, schema='incidents')
    op.create_index(op.f('ix_incidents_incidents_priority'), 'incidents', ['priority'], unique=False, schema='incidents')
    op.create_index('ix_incidents_priority_status', 'incidents', ['priority', 'status'], unique=False, schema='incidents')
    op.create_index('ix_incidents_service_started', 'incidents', ['service_id', 'started_at'], unique=False, schema='incidents')
    op.create_index('ix_incidents_status_severity', 'incidents', ['status', 'severity'], unique=False, schema='incidents')
    op.drop_column('incidents', 'opened_at', schema='incidents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='incidents')
    op.drop_index('ix_incidents_status_severity', table_name='incidents', schema='incidents')
    op.drop_index('ix_incidents_service_started', table_name='incidents', schema='incidents')
    op.drop_index('ix_incidents_priority_status', table_name='incidents', schema='incidents')
    op.drop_index(op.f('ix_incidents_incidents_priority'), table_name='incidents', schema='incidents')
    op.drop_index(op.f('ix_incidents_incidents_incident_type'), table_name='incidents', schema='incidents')
    op.drop_index(op.f('ix_incidents_incidents_incident_number'), table_name='incidents', schema='incidents')
    op.drop_column('incidents', 'sla_breached', schema='incidents')
    op.drop_column('incidents', 'duration_minutes', schema='incidents')
    op.drop_column('incidents', 'detected_at', schema='incidents')
    op.drop_column('incidents', 'started_at', schema='incidents')
    op.drop_column('incidents', 'resolution_summary', schema='incidents')
    op.drop_column('incidents', 'customer_impact', schema='incidents')
    op.drop_column('incidents', 'root_cause', schema='incidents')
    op.drop_column('incidents', 'detected_by', schema='incidents')
    op.drop_column('incidents', 'priority', schema='incidents')
    op.drop_column('incidents', 'incident_type', schema='incidents')
    op.drop_column('incidents', 'incident_number', schema='incidents')
    # ### end Alembic commands ###
