"""add operations platform models

Revision ID: 9d34befbf905
Revises: 35e9d09a065b
Create Date: 2026-07-19 21:16:48.460609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d34befbf905'
down_revision: Union[str, Sequence[str], None] = '35e9d09a065b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_number', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=150), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outage_expected', sa.Boolean(), nullable=False),
    sa.Column('customer_notification_required', sa.Boolean(), nullable=False),
    sa.Column('customer_notification_sent', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index('ix_maintenance_windows_environment_status', 'maintenance_windows', ['environment', 'status'], unique=False, schema='operations')
    op.create_index('ix_maintenance_windows_service_schedule', 'maintenance_windows', ['service_id', 'scheduled_start_at'], unique=False, schema='operations')
    op.create_index('ix_maintenance_windows_status_schedule', 'maintenance_windows', ['status', 'scheduled_start_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_approved_by'), 'maintenance_windows', ['approved_by'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_correlation_id'), 'maintenance_windows', ['correlation_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_environment'), 'maintenance_windows', ['environment'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_maintenance_number'), 'maintenance_windows', ['maintenance_number'], unique=True, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_maintenance_type'), 'maintenance_windows', ['maintenance_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_requested_by'), 'maintenance_windows', ['requested_by'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_scheduled_start_at'), 'maintenance_windows', ['scheduled_start_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_service_id'), 'maintenance_windows', ['service_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_maintenance_windows_status'), 'maintenance_windows', ['status'], unique=False, schema='operations')
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_number', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_window_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('previous_version', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('deployment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('initiated_by', sa.String(length=150), nullable=False),
    sa.Column('source_branch', sa.String(length=150), nullable=True),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('deployment_notes', sa.Text(), nullable=True),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_completed', sa.Boolean(), nullable=False),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['incidents.changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_window_id'], ['operations.maintenance_windows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index('ix_deployments_change_id', 'deployments', ['change_id'], unique=False, schema='operations')
    op.create_index('ix_deployments_maintenance_window_id', 'deployments', ['maintenance_window_id'], unique=False, schema='operations')
    op.create_index('ix_deployments_service_started_at', 'deployments', ['service_id', 'started_at'], unique=False, schema='operations')
    op.create_index('ix_deployments_status_environment', 'deployments', ['status', 'environment'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_commit_sha'), 'deployments', ['commit_sha'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_correlation_id'), 'deployments', ['correlation_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_deployment_number'), 'deployments', ['deployment_number'], unique=True, schema='operations')
    op.create_index(op.f('ix_operations_deployments_deployment_type'), 'deployments', ['deployment_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_environment'), 'deployments', ['environment'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_initiated_by'), 'deployments', ['initiated_by'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_service_id'), 'deployments', ['service_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_started_at'), 'deployments', ['started_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_status'), 'deployments', ['status'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_deployments_version'), 'deployments', ['version'], unique=False, schema='operations')
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_number', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('change_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('source_service', sa.String(length=150), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['incidents.changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['operations.deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index('ix_audit_events_actor_occurred_at', 'audit_events', ['actor_name', 'occurred_at'], unique=False, schema='operations')
    op.create_index('ix_audit_events_correlation_id', 'audit_events', ['correlation_id'], unique=False, schema='operations')
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False, schema='operations')
    op.create_index('ix_audit_events_event_type_occurred_at', 'audit_events', ['event_type', 'occurred_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_action'), 'audit_events', ['action'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_actor_name'), 'audit_events', ['actor_name'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_audit_number'), 'audit_events', ['audit_number'], unique=True, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_change_id'), 'audit_events', ['change_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_deployment_id'), 'audit_events', ['deployment_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_event_type'), 'audit_events', ['event_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_outcome'), 'audit_events', ['outcome'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_service_id'), 'audit_events', ['service_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_audit_events_source_service'), 'audit_events', ['source_service'], unique=False, schema='operations')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_number', sa.String(length=30), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('audit_event_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=250), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_event_id'], ['operations.audit_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['operations.deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['registry.services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_index('ix_notifications_correlation_id', 'notifications', ['correlation_id'], unique=False, schema='operations')
    op.create_index('ix_notifications_service_created_at', 'notifications', ['service_id', 'created_at'], unique=False, schema='operations')
    op.create_index('ix_notifications_status_scheduled_at', 'notifications', ['status', 'scheduled_at'], unique=False, schema='operations')
    op.create_index('ix_notifications_type_priority', 'notifications', ['notification_type', 'priority'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_audit_event_id'), 'notifications', ['audit_event_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_channel'), 'notifications', ['channel'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_created_at'), 'notifications', ['created_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_deployment_id'), 'notifications', ['deployment_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_incident_id'), 'notifications', ['incident_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_notification_number'), 'notifications', ['notification_number'], unique=True, schema='operations')
    op.create_index(op.f('ix_operations_notifications_notification_type'), 'notifications', ['notification_type'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_priority'), 'notifications', ['priority'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_recipient'), 'notifications', ['recipient'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_service_id'), 'notifications', ['service_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_notifications_status'), 'notifications', ['status'], unique=False, schema='operations')

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(op.f('ix_operations_notifications_status'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_service_id'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_scheduled_at'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_recipient'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_priority'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_notification_type'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_notification_number'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_incident_id'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_deployment_id'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_created_at'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_channel'), table_name='notifications', schema='operations')
    op.drop_index(op.f('ix_operations_notifications_audit_event_id'), table_name='notifications', schema='operations')
    op.drop_index('ix_notifications_type_priority', table_name='notifications', schema='operations')
    op.drop_index('ix_notifications_status_scheduled_at', table_name='notifications', schema='operations')
    op.drop_index('ix_notifications_service_created_at', table_name='notifications', schema='operations')
    op.drop_index('ix_notifications_correlation_id', table_name='notifications', schema='operations')
    op.drop_table('notifications', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_source_service'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_service_id'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_outcome'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_occurred_at'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_incident_id'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_event_type'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_entity_type'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_deployment_id'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_change_id'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_audit_number'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_actor_type'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_actor_name'), table_name='audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_audit_events_action'), table_name='audit_events', schema='operations')
    op.drop_index('ix_audit_events_event_type_occurred_at', table_name='audit_events', schema='operations')
    op.drop_index('ix_audit_events_entity', table_name='audit_events', schema='operations')
    op.drop_index('ix_audit_events_correlation_id', table_name='audit_events', schema='operations')
    op.drop_index('ix_audit_events_actor_occurred_at', table_name='audit_events', schema='operations')
    op.drop_table('audit_events', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_version'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_status'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_started_at'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_service_id'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_initiated_by'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_environment'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_deployment_type'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_deployment_number'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_correlation_id'), table_name='deployments', schema='operations')
    op.drop_index(op.f('ix_operations_deployments_commit_sha'), table_name='deployments', schema='operations')
    op.drop_index('ix_deployments_status_environment', table_name='deployments', schema='operations')
    op.drop_index('ix_deployments_service_started_at', table_name='deployments', schema='operations')
    op.drop_index('ix_deployments_maintenance_window_id', table_name='deployments', schema='operations')
    op.drop_index('ix_deployments_change_id', table_name='deployments', schema='operations')
    op.drop_table('deployments', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_status'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_service_id'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_scheduled_start_at'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_requested_by'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_maintenance_type'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_maintenance_number'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_environment'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_correlation_id'), table_name='maintenance_windows', schema='operations')
    op.drop_index(op.f('ix_operations_maintenance_windows_approved_by'), table_name='maintenance_windows', schema='operations')
    op.drop_index('ix_maintenance_windows_status_schedule', table_name='maintenance_windows', schema='operations')
    op.drop_index('ix_maintenance_windows_service_schedule', table_name='maintenance_windows', schema='operations')
    op.drop_index('ix_maintenance_windows_environment_status', table_name='maintenance_windows', schema='operations')
    op.drop_table('maintenance_windows', schema='operations')
    # ### end Alembic commands ###
