"""Add service metrics composite index

Revision ID: f2be6dd724e8
Revises: 7f9700c8c034
Create Date: 2026-07-17 13:34:44.162011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2be6dd724e8'
down_revision: Union[str, Sequence[str], None] = '7f9700c8c034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_metrics_service_recorded_at', 'service_metrics', ['service_id', 'recorded_at'], unique=False, schema='registry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_metrics_service_recorded_at', table_name='service_metrics', schema='registry')
    # ### end Alembic commands ###
