"""create identity database tables

Revision ID: 3b66fc055854
Revises: 
Create Date: 2026-07-13 17:12:47.165106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b66fc055854'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity',
    comment='Stores approved NEXUS platform roles.'
    )
    op.create_index(op.f('ix_identity_roles_name'), 'roles', ['name'], unique=True, schema='identity')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity',
    comment='Stores NEXUS platform user accounts.'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_is_active'), 'users', ['is_active'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_users_role_id'), 'users', ['role_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_users_username'), 'users', ['username'], unique=True, schema='identity')
    op.create_table('authentication_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity',
    comment='Stores login, logout, token, and authorization-related events.'
    )
    op.create_index(op.f('ix_identity_authentication_events_correlation_id'), 'authentication_events', ['correlation_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_authentication_events_created_at'), 'authentication_events', ['created_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_authentication_events_event_type'), 'authentication_events', ['event_type'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_authentication_events_result'), 'authentication_events', ['result'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_authentication_events_user_id'), 'authentication_events', ['user_id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_authentication_events_user_id'), table_name='authentication_events', schema='identity')
    op.drop_index(op.f('ix_identity_authentication_events_result'), table_name='authentication_events', schema='identity')
    op.drop_index(op.f('ix_identity_authentication_events_event_type'), table_name='authentication_events', schema='identity')
    op.drop_index(op.f('ix_identity_authentication_events_created_at'), table_name='authentication_events', schema='identity')
    op.drop_index(op.f('ix_identity_authentication_events_correlation_id'), table_name='authentication_events', schema='identity')
    op.drop_table('authentication_events', schema='identity')
    op.drop_index(op.f('ix_identity_users_username'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_role_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_is_active'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_index(op.f('ix_identity_roles_name'), table_name='roles', schema='identity')
    op.drop_table('roles', schema='identity')
    # ### end Alembic commands ###
