"""Database model for operational notifications."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database.base import Base


class Notification(Base):
    """Represents an operational notification generated by NEXUS."""

    __tablename__ = "notifications"
    __table_args__ = (
        Index(
            "ix_notifications_status_scheduled_at",
            "status",
            "scheduled_at",
        ),
        Index(
            "ix_notifications_service_created_at",
            "service_id",
            "created_at",
        ),
        Index(
            "ix_notifications_type_priority",
            "notification_type",
            "priority",
        ),
        Index(
            "ix_notifications_correlation_id",
            "correlation_id",
        ),
        {"schema": "operations"},
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    notification_number = Column(
        String(30),
        nullable=False,
        unique=True,
        index=True,
    )

    service_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "registry.services.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    incident_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "incidents.incidents.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    deployment_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "operations.deployments.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    audit_event_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "operations.audit_events.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    notification_type = Column(
        String(100),
        nullable=False,
        index=True,
    )

    channel = Column(
        String(50),
        nullable=False,
        default="InApplication",
        index=True,
    )

    recipient = Column(
        String(250),
        nullable=True,
        index=True,
    )

    subject = Column(
        String(250),
        nullable=False,
    )

    message = Column(
        Text,
        nullable=False,
    )

    priority = Column(
        String(25),
        nullable=False,
        default="Normal",
        index=True,
    )

    status = Column(
        String(50),
        nullable=False,
        default="Pending",
        index=True,
    )

    retry_count = Column(
        Integer,
        nullable=False,
        default=0,
    )

    max_retries = Column(
        Integer,
        nullable=False,
        default=3,
    )

    scheduled_at = Column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    processing_started_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    sent_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    failed_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    failure_reason = Column(
        Text,
        nullable=True,
    )

    correlation_id = Column(
        String(100),
        nullable=True,
    )

    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        index=True,
    )

    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    service = relationship(
        "Service",
        back_populates="notifications",
    )

    incident = relationship(
        "Incident",
    )

    deployment = relationship(
        "Deployment",
        back_populates="notifications",
    )

    audit_event = relationship(
        "AuditEvent",
        back_populates="notifications",
    )

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __repr__(self):
        return (
            f"<Notification("
            f"notification_number='{self.notification_number}', "
            f"type='{self.notification_type}', "
            f"status='{self.status}', "
            f"priority='{self.priority}'"
            f")>"
        )